### ISSUE TITLE
你每张图片对应着的json文件是怎么得到的。

### ISSUE THREAD

**Issue by 1691077362** [weizheliu/People-Flows#6]
你每张图片对应着的json文件是怎么得到的。麻烦大神帮忙解决一下

**Comment by weizheliu** [comment]
你好，

JSON 文件不是针对一张图的，而是针对一个数据集的。

具体的步骤是：
1. 下载数据集
2. 用‘make_dataset.py’ 这个代码去把数据集转成hdf5格式，这样方便load
3. 用‘create_json.py’， 这个代码去生成训练集，验证集和测试集。换句话说，一共生成3个json文件（train.json,val.json,test.json），而不是每个图片生成一个文件.   json 文件只有数据集分组信息，数据地址信息，并没有每个图片的具体信息。
4. 跑实验

在每一步需要保证数据集路径设置正确。

**Comment by 1691077362** [comment]
@weizheliu 你给的数据集里的图片不是有每张图片都有一个对应的json文件吗，我想知道那个json文件是怎么得来的。
![捕获](https://user-images.githubusercontent.com/91247734/139223748-41ee3f94-84e0-4ef5-bab7-c13f6c6b2db3.PNG)

**Comment by weizheliu** [comment]
不好意思哈，这个FDST数据集不是我们release的，所以我并不知道他们是怎么生成这个json文件的，如果有疑问可以直接去问这篇[论文](https://arxiv.org/pdf/1907.07911v1.pdf)的作者。

**Comment by 1691077362** [comment]
好的谢谢
